### ISSUE TITLE
Readme links https://songbook.tumbolia.tk/#/intro timeouts

### ISSUE THREAD

**Issue by MartyLake** [AnotherKamila/songbook-web#1]
Hello!
wanted to check the link in the readme, but my browser timeouts.

**Comment by AnotherKamila** [comment]
Hi,

my domain somehow expired, I'll have to get it back. Will look at it probably today or tomorrow.

**Comment by AnotherKamila** [comment]
Hi,

my domain is back, but my SSL certs are a mess :D so I changed the link to https://spevnik.tumbolia.tk/#/intro , which now works :-)
